# Build stage
# FROM node:latest as build-stage

FROM node:24-alpine as build-stage

WORKDIR /app

COPY package*.json ./

RUN npm install

# Copy all files in this project to working directory of Docker container
COPY . .

RUN npm run build

# Production stage
FROM node:24-alpine as production-stage

WORKDIR /app

COPY --from=build-stage /app/dist /app
COPY --from=build-stage /app/package*.json ./

RUN npm install --production
RUN npm install pm2 -g

# The port of Docker
EXPOSE  3000

CMD ["pm2-runtime", "/app/main.js"]
